=== JeanCastro01/Music-Table/mytable.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="musictable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="music" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Artistname"/>
              <xs:element type="xs:string" name="Albumname"/>
              <xs:element type="xs:short" name="YearOfRelease"/>
              <xs:element type="xs:string" name="RecordLabelName"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JeanCastro01/Music-Table/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="mytable.xsl"?>
<musictable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mytable.xsd">


   <music>
      <Artistname>Artdate1</Artistname>
      <Albumname>Hands Up</Albumname>
      <YearOfRelease>2020</YearOfRelease>
      <RecordLabelName>Fish And Chick's</RecordLabelName>
   </music>
      <music>
      <Artistname>Artdate1</Artistname>
      <Albumname>Hands Up</Albumname>
      <YearOfRelease>2020</YearOfRelease>
      <RecordLabelName>Fish And Chick's</RecordLabelName>
   </music>

   
</musictable>
